### ISSUE TITLE
unique_id

### ISSUE THREAD

**Issue by dbozec** [fredericvl/pyevacalor#1]
Hi,

what is the unique_id required ?
How can I get one ?

Thanks

**Comment by fredericvl** [comment]
Hi @dbozec 

The unique_id parameter is an UUID that is used to register a fake phone app at the API side (needed to get everything working).
You can use this site to generate a random one: https://www.uuidgenerator.net/version4

Greets!

**Comment by dbozec** [comment]
Thank you !

**Comment by jorgesousa1975** [comment]
> Hi @dbozec
> 
> The unique_id parameter is an UUID that is used to register a fake phone app at the API side (needed to get everything working).
> You can use this site to generate a random one: https://www.uuidgenerator.net/version4
> 
> Greets!

Do you happen to have some instructions to install the pyevacalor?

**Comment by fredericvl** [comment]
> Do you happen to have some instructions to install the pyevacalor?

@jorgesousa1975: I've added example usage for Python and also added an optional example to use it within Home Assistant if you are interested.

**Comment by jorgesousa1975** [comment]
> > Do you happen to have some instructions to install the pyevacalor?
> 
> @jorgesousa1975: I've added example usage for Python and also added an optional example to use it within Home Assistant if you are interested.

I did so far ok, but then "Open the Home Assistant web interface and go to Integrations and add the Eva Calor integration using your email address and password that you use to login and manage your Eva Calor heating device." the Eva Calor integration is not available.

**Comment by KarlB59** [comment]
Hi Frederic, 

Very good job for your code.
Actually i test your code for adapt on Jeedom (alternative home assistant).
I think you can add a new parameter for change a REG CODE, because i think this variable is differente on anywhere other evacalor.
for example :
for you : EVA_CALOR_CUSTOMER_CODE = "635987"
for me : EVA_CALOR_CUSTOMER_CODE = "656217"
This data is givving by my installer

What do you think ?

PS : thank you for your add example, i test asap.

**Comment by fredericvl** [comment]
> Hi Frederic,
> 
> Very good job for your code.
> Actually i test your code for adapt on Jeedom (alternative home assistant).
> I think you can add a new parameter for change a REG CODE, because i think this variable is differente on anywhere other evacalor.
> for example :
> for you : EVA_CALOR_CUSTOMER_CODE = "635987"
> for me : EVA_CALOR_CUSTOMER_CODE = "656217"
> This data is givving by my installer
> 
> What do you think ?
> 
> PS : thank you for your add example, i test asap.

Hi @KarlB59,

I'm aware that the customer code (and also the API URL in some cases) should have a different value per stove brand.
Actually the intention of this module "pyevacalor", like it is in the name, is to get it working for Eva Calor stoves.

Maybe it's an idea to create a separate Python module where the API URL & customer code are adjustable in the init so they can be changed accordingly.

Greetz!

**Comment by fredericvl** [comment]
> I did so far ok, but then "Open the Home Assistant web interface and go to Integrations and add the Eva Calor integration using your email address and password that you use to login and manage your Eva Calor heating device." the Eva Calor integration is not available.

@jorgesousa1975:
Anything (errors, warnings) in the Home Assistant logs?
Also, do you own a Eva Calor stove or is it a different brand?
Because this module will only work with Eva Calor stoves (see my post above).

**Comment by jorgesousa1975** [comment]
Yes, I have an EvaCalòr tommy. But I’m very new on Home Assistant, so I’m not understanding where todo that last step

**Comment by jorgesousa1975** [comment]
Got it now. Greag
